dist: trusty
os: linux
language: node_js
node_js:
- '8'
cache: 
directories:
- node_modules
before_install:
- sudo add-apt-repository ppa:ubuntu-wine/ppa -y
- sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
- echo "deb http://download.mono-project.com/repo/debian wheezy main" | sudo tee /etc/apt/sources.list.d/mono-xamarin.list
- sudo apt-get update
- sudo apt-get install --no-install-recommends -y mono-devel ca-certificates-mono
  wine1.8 gcc-multilib g++-multilib
script:
- npm install -g bower
- npm update -g npm
- bower install
- npm run package-linux
- npm run package-mac
- npm run package-windows
before_deploy:
- cd build
- bash ../script/zip.sh
- export RELEASE_PKG_FILE=$(ls *.zip)
- echo "deploying $RELEASE_PKG_FILE to GitHub releases"
deploy:
  - provider: releases
    api_key:
      secure: hnnSFIJEjxGomMy17co5OmWTMAy3vaH3zPat7/mU5X+jz5sq/Q2SuZCdFu2Hd6T5HklWzYesn/OoZp+t2rN1U9XK9aZfUc3BRM5bMgwK1U46PeiAkvgWhXdiCu/vE1XVtJjCC4VxREZYMjeCo2BFLIzkxAW/Bm9YvqvK6LCjDt2NQ0uMgzv1IgWRhrMh+zR2Xx6Wv9M4RohxkF0GYluBq7mKURSfp/OpYcoe+vA/0/ObZkoAjX7Q/gp++QPvr8ZJdEIQTx7k9OyS/KryBGbpMaZ43+A0b7XHts+Wgg0fUuEv2sOw8o3zA9u4bVxupbutcWyeeryAL18AwYounBg17tfSHbVubn8KyfwPl1lFRxhi6abtz15S92vIoiuuecU1UlEvNQEJcwgyoR7OclVmlH/pknjVVL9zVKvZ8jT5hmExLVHVSX2cBYyN1f36SLGxyGtEd8lSG1LFEHVnWCqRMume66gvIKTwmVI5olG6DSiR97BNjMuGsQQgl41Wdr77slu0iKh0B7WJgDHPv8hsukB3wC+T7SzlN2sKFU48qw9GK+wwqexfEYfp0CbHA84dbqrEGTUqRKoL7iQqJEKrGMFsWKW2p9tCBVtd2edO/aD+cugNw7i717faqSbeEj9fCa+9UC01pa2IWyRcSXW/Vw5nX1a1uPiYEC30yO/mlKY=
    skip_cleanup: true
    file_glob: true
    file: "*.zip"
    on:
      branch: master
  - provider: releases
    api_key:
      secure: hnnSFIJEjxGomMy17co5OmWTMAy3vaH3zPat7/mU5X+jz5sq/Q2SuZCdFu2Hd6T5HklWzYesn/OoZp+t2rN1U9XK9aZfUc3BRM5bMgwK1U46PeiAkvgWhXdiCu/vE1XVtJjCC4VxREZYMjeCo2BFLIzkxAW/Bm9YvqvK6LCjDt2NQ0uMgzv1IgWRhrMh+zR2Xx6Wv9M4RohxkF0GYluBq7mKURSfp/OpYcoe+vA/0/ObZkoAjX7Q/gp++QPvr8ZJdEIQTx7k9OyS/KryBGbpMaZ43+A0b7XHts+Wgg0fUuEv2sOw8o3zA9u4bVxupbutcWyeeryAL18AwYounBg17tfSHbVubn8KyfwPl1lFRxhi6abtz15S92vIoiuuecU1UlEvNQEJcwgyoR7OclVmlH/pknjVVL9zVKvZ8jT5hmExLVHVSX2cBYyN1f36SLGxyGtEd8lSG1LFEHVnWCqRMume66gvIKTwmVI5olG6DSiR97BNjMuGsQQgl41Wdr77slu0iKh0B7WJgDHPv8hsukB3wC+T7SzlN2sKFU48qw9GK+wwqexfEYfp0CbHA84dbqrEGTUqRKoL7iQqJEKrGMFsWKW2p9tCBVtd2edO/aD+cugNw7i717faqSbeEj9fCa+9UC01pa2IWyRcSXW/Vw5nX1a1uPiYEC30yO/mlKY=
    skip_cleanup: true
    file_glob: true
    file: "*.zip"
    on:
      tags: true